// 정답 리스트
export const ANSWERS = [
  "Banana",
  "Computer",
  "Elephant",
  "Tiger",
  "Bicycle",
  "Smartphone",
  "Chocolate",
  "Ice cream",
  "Rainbow",
  "Moonlight",
  "Cinema",
  "Holiday",
  "Spaceship",
  "Stadium",
  "Automobile",
  "Cactus",
  "Post office",
  "Algorithm",
  "WiFi",
  "Weather forecast",
].map((answer) => answer.toUpperCase());